spring:
  application:
    name: blog
  datasource:
    url: jdbc:mariadb://localhost:3306/blog
    username: blog
    password: blog1234
    driver-class-name: org.mariadb.jdbc.Driver

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui
    operations-sorter: method
    tags-sorter: alpha
